/*
 * Decompiled with CFR 0.152.
 */
package shit.manager;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import shit.misc.BaritoneProcess;
import shit.misc.Biome;
import shit.misc.CPS;
import shit.misc.Direction;
import shit.misc.Durability;
import shit.misc.EntityList;
import shit.misc.Memory;
import shit.misc.PlayerSpeed;
import shit.misc.Rotation;
import shit.misc.ServerBrand;
import shit.misc.TPS;
import shit.misc.TextRadar;
import shit.misc.Time;
import shit.misc.TimerSpeed;
import shit.misc.Username;
import shit.misc.WorldTime;
import shit.module.Category;
import shit.module.Module;
import shit.module.chat.AntiSpam;
import shit.module.chat.AutoCope;
import shit.module.chat.AutoQMain;
import shit.module.chat.AutoReply;
import shit.module.chat.ChatSuffix;
import shit.module.chat.ChatTimestamp;
import shit.module.chat.Emoji;
import shit.module.chat.ExtraChatHistory;
import shit.module.chat.FancyChat;
import shit.module.chat.LoginMessage;
import shit.module.chat.PortalChat;
import shit.module.chat.Spammer;
import shit.module.client.ClickGUI;
import shit.module.client.ClientSetting;
import shit.module.client.Fonts;
import shit.module.client.HudEditor;
import shit.module.client.MainMenu;
import shit.module.client.SettingTest;
import shit.module.client.Skin;
import shit.module.combat.AntiBot;
import shit.module.combat.AntiRegear;
import shit.module.misc.AutoEZ;
import shit.module.combat.AutoHoleFill;
import shit.module.combat.AutoKit;
import shit.module.combat.AutoMend;
import shit.module.combat.AutoMine;
import shit.module.combat.AutoRegear;
import shit.module.combat.AutoTrap;
import shit.module.combat.Burrow;
import shit.module.combat.Criticals;
import shit.module.combat.CrystalChams;
import shit.module.combat.HandManager;
import shit.module.combat.HoleESP;
import shit.module.combat.KillAura;
import shit.module.combat.MidClickPearl;
import shit.module.combat.Surround;
import shit.module.combat.TotemPopCounter;
import shit.module.combat.VisualRange;
import shit.module.combat.WebAura;
import shit.module.combat.ZealotCrystalPlus;
import shit.module.exploit.AntiHunger;
import shit.module.exploit.CornerClip;
import shit.module.exploit.Disabler;
import shit.module.exploit.HighJump;
import shit.module.exploit.MaceSpoof;
import shit.module.exploit.MountBypass;
import shit.module.exploit.Phase;
import shit.module.exploit.PingSpoof;
import shit.module.exploit.WallClip;
import shit.module.exploit.XCarry;
import shit.module.exploit._32kMace;
import shit.module.hud.ArmorHud;
import shit.module.hud.AutoRegearHud;
import shit.module.hud.CombatItemCount;
import shit.module.hud.Coordinates;
import shit.module.hud.FPS;
import shit.module.hud.InventoryViewer;
import shit.module.hud.IrcChatHUD;
import shit.module.hud.Notification;
import shit.module.hud.Ping;
import shit.module.hud.PlayerModel;
import shit.module.hud.Radar;
import shit.module.hud.TotemHud;
import shit.module.hud.Watermark;
import shit.module.misc.AntiAFK;
import shit.module.misc.AntiBookKick;
import shit.module.misc.AutoFish;
import shit.module.misc.AutoLog;
import shit.module.misc.AutoReconnect;
import shit.module.misc.AutoRespawn;
import shit.module.misc.AutoTool;
import shit.module.misc.BreakWarning;
import shit.module.misc.CoordsLog;
import shit.module.misc.FakeGameMode;
import shit.module.misc.FakePlayer;
import shit.module.misc.FakeVanillaClient;
import shit.module.misc.Friend;
import shit.module.misc.IRC;
import shit.module.misc.KillEffect;
import shit.module.misc.LogoutLogger;
import shit.module.misc.NoSoundLag;
import shit.module.misc.Punctuation;
import shit.module.misc.ShulkerViewer;
import shit.module.misc.SkinBlinker;
import shit.module.misc.StashLogger;
import shit.module.misc.TeleportLogger;
import shit.module.misc.Tips;
import shit.module.misc.UnfocusedFps;
import shit.module.movement.Anchor;
import shit.module.movement.AntiLevitation;
import shit.module.movement.AutoCenter;
import shit.module.movement.AutoJump;
import shit.module.movement.AutoRemount;
import shit.module.movement.AutoSprint;
import shit.module.movement.AutoWalk;
import shit.module.movement.BlockStrafe;
import shit.module.movement.ElytraFly;
import shit.module.movement.ElytraReplace;
import shit.module.movement.EntitySpeed;
import shit.module.movement.FastSwim;
import shit.module.movement.FastWeb;
import shit.module.movement.Flight;
import shit.module.movement.HoleSnap;
import shit.module.movement.InMove;
import shit.module.movement.Jesus;
import shit.module.movement.NoSlow;
import shit.module.movement.ReverseStep;
import shit.module.movement.SafeWalk;
import shit.module.movement.Speed;
import shit.module.movement.Step;
import shit.module.movement.Strafe;
import shit.module.movement.Timer;
import shit.module.movement.VClip;
import shit.module.movement.Velocity;
import shit.module.player.AntiEffects;
import shit.module.player.AutoArmor;
import shit.module.player.AutoEat;
import shit.module.player.AutoEject;
import shit.module.player.AutoPot;
import shit.module.player.Blink;
import shit.module.player.ChestStealer;
import shit.module.player.FastUse;
import shit.module.player.HandSwing;
import shit.module.player.InteractTweaks;
import shit.module.player.ItemSaver;
import shit.module.player.LagNotifier;
import shit.module.player.MotionLogger;
import shit.module.player.NoFall;
import shit.module.player.NoPacketKick;
import shit.module.player.NoRotate;
import shit.module.player.PacketCancel;
import shit.module.player.PacketLimiter;
import shit.module.player.PacketLogger;
import shit.module.player.Replenish;
import shit.module.player.Scaffold;
import shit.module.player.SpeedMine;
import shit.module.player.SwingLimiter;
import shit.module.player.ViewLock;
import shit.module.render.Ambience;
import shit.module.render.AntiFog;
import shit.module.render.AntiOverlay;
import shit.module.render.ArmorHide;
import shit.module.render.BreakESP;
import shit.module.render.Camera;
import shit.module.render.Chams;
import shit.module.render.ChestESP;
import shit.module.render.ExtraTab;
import shit.module.render.Fullbright;
import shit.module.render.MobOwner;
import shit.module.render.NameTags;
import shit.module.render.NoRender;
import shit.module.render.PlaceRender;
import shit.module.render.SelectionHighlight;
import shit.module.render.Shaders;
import shit.module.render.TotemParticle;
import shit.module.render.ViewModel;
import shit.module.render.VoidESP;

@Environment(value=EnvType.CLIENT)
public class ModuleManager {
    private final List list20 = new ArrayList();

    public void init() {
        this.setObj16(new shit.module.chat.AntiSpam());
        this.setObj16(new shit.module.chat.AutoCope());
        this.setObj16(new shit.module.chat.AutoQMain());
        this.setObj16(new shit.module.chat.ChatSuffix());
        this.setObj16(new shit.module.chat.ChatTimestamp());
        this.setObj16(new shit.module.chat.Emoji());
        this.setObj16(new shit.module.chat.FancyChat());
        this.setObj16(new shit.module.chat.LoginMessage());
        this.setObj16(new shit.module.chat.AutoReply());
        this.setObj16(new shit.module.chat.ExtraChatHistory());
        this.setObj16(new shit.module.chat.PortalChat());
        this.setObj16(new shit.module.chat.Spammer());
        this.setObj16(new shit.module.client.ClientSetting());
        this.setObj16(new shit.module.client.ClickGUI());
        this.setObj16(new shit.module.client.Fonts());
        this.setObj16(new shit.module.client.HudEditor());
        this.setObj16(new shit.module.client.MainMenu());
        this.setObj16(new shit.module.client.Skin());
        this.setObj16(new shit.module.client.SettingTest());
        this.setObj16(new shit.module.hud.ArrayList());
        this.setObj16(new shit.module.hud.FPS());
        this.setObj16(new shit.module.hud.Ping());
        this.setObj16(new shit.module.hud.ArmorHud());
        this.setObj16(new shit.module.hud.Watermark());
        this.setObj16(new shit.module.hud.Notification());
        this.setObj16(new shit.module.hud.Coordinates());
        this.setObj16(new shit.misc.Username());
        this.setObj16(new shit.misc.Memory());
        this.setObj16(new shit.misc.ServerBrand());
        this.setObj16(new shit.misc.BaritoneProcess());
        this.setObj16(new shit.misc.Time());
        this.setObj16(new shit.misc.TPS());
        this.setObj16(new shit.misc.Direction());
        this.setObj16(new shit.misc.Durability());
        this.setObj16(new shit.misc.PlayerSpeed());
        this.setObj16(new shit.misc.Rotation());
        this.setObj16(new shit.misc.TimerSpeed());
        this.setObj16(new shit.misc.Biome());
        this.setObj16(new shit.misc.EntityList());
        this.setObj16(new shit.misc.TextRadar());
        this.setObj16(new shit.misc.CPS());
        this.setObj16(new shit.misc.WorldTime());
        this.setObj16(new shit.module.render.MobOwner());
        this.setObj16(new shit.module.hud.InventoryViewer());
        this.setObj16(new shit.module.hud.AutoRegearHud());
        this.setObj16(new shit.module.hud.Radar());
        this.setObj16(new shit.module.hud.CombatItemCount());
        this.setObj16(new shit.module.hud.PlayerModel());
        this.setObj16(new shit.module.exploit.HighJump());
        this.setObj16(new shit.module.hud.TotemHud());
        this.setObj16(new shit.module.movement.AutoSprint());
        this.setObj16(new shit.module.movement.Anchor());
        this.setObj16(new shit.module.movement.AntiLevitation());
        this.setObj16(new shit.module.movement.AutoCenter());
        this.setObj16(new shit.module.movement.AutoJump());
        this.setObj16(new shit.module.movement.AutoRemount());
        this.setObj16(new shit.module.movement.AutoWalk());
        this.setObj16(new shit.module.movement.ElytraReplace());
        this.setObj16(new shit.module.movement.EntitySpeed());
        this.setObj16(new shit.module.movement.Flight());
        this.setObj16(new shit.module.movement.NoSlow());
        this.setObj16(new shit.module.movement.InMove());
        this.setObj16(new shit.module.misc.FakePlayer());
        this.setObj16(new shit.module.movement.Speed());
        this.setObj16(new shit.module.movement.Step());
        this.setObj16(new shit.module.movement.Strafe());
        this.setObj16(new shit.module.movement.BlockStrafe());
        this.setObj16(new shit.module.movement.HoleSnap());
        this.setObj16(new shit.module.movement.Velocity());
        this.setObj16(new shit.module.movement.FastSwim());
        this.setObj16(new shit.module.movement.Jesus());
        this.setObj16(new shit.module.movement.ReverseStep());
        this.setObj16(new shit.module.movement.SafeWalk());
        this.setObj16(new shit.module.player.NoFall());
        this.setObj16(new shit.module.player.Scaffold());
        this.setObj16(new shit.module.combat.Surround());
        this.setObj16(new shit.module.combat.Burrow());
        this.setObj16(new shit.module.render.Fullbright());
        this.setObj16(new shit.module.combat.Criticals());
        this.setObj16(new shit.module.combat.HandManager());
        this.setObj16(new shit.module.combat.CrystalChams());
        this.setObj16(new shit.module.combat.HoleESP());
        this.setObj16(new shit.module.player.AutoPot());
        this.setObj16(new shit.module.player.SpeedMine());
        this.setObj16(new shit.module.combat.AutoMine());
        this.setObj16(new shit.module.player.InteractTweaks());
        this.setObj16(new shit.module.movement.Timer());
        this.setObj16(new shit.module.combat.ZealotCrystalPlus());
        this.setObj16(new shit.module.combat.AntiBot());
        this.setObj16(new shit.module.misc.AutoEZ());
        this.setObj16(new shit.module.combat.AutoHoleFill());
        this.setObj16(new shit.module.combat.WebAura());
        this.setObj16(new shit.module.combat.AutoKit());
        this.setObj16(new shit.module.combat.AutoMend());
        this.setObj16(new shit.module.combat.KillAura());
        this.setObj16(new shit.module.combat.MidClickPearl());
        this.setObj16(new shit.module.combat.TotemPopCounter());
        this.setObj16(new shit.module.combat.VisualRange());
        this.setObj16(new shit.module.render.AntiFog());
        this.setObj16(new shit.module.render.AntiOverlay());
        this.setObj16(new shit.module.render.ArmorHide());
        this.setObj16(new shit.module.render.BreakESP());
        this.setObj16(new shit.module.render.ChestESP());
        this.setObj16(new shit.module.render.Chams());
        this.setObj16(new shit.module.render.PlaceRender());
        this.setObj16(new shit.module.render.NoRender());
        this.setObj16(new shit.module.render.Camera());
        this.setObj16(new shit.module.render.Ambience());
        this.setObj16(new shit.module.render.Shaders());
        this.setObj16(new shit.module.render.SelectionHighlight());
        this.setObj16(new shit.module.render.ViewModel());
        this.setObj16(new shit.module.render.TotemParticle());
        this.setObj16(new shit.module.movement.ElytraFly());
        this.setObj16(new shit.module.player.AutoArmor());
        this.setObj16(new shit.module.misc.Friend());
        this.setObj16(new shit.module.misc.IRC());
        this.setObj16(new shit.module.hud.IrcChatHUD());
        this.setObj16(new shit.module.misc.AntiAFK());
        this.setObj16(new shit.module.misc.AntiBookKick());
        this.setObj16(new shit.module.misc.AutoFish());
        this.setObj16(new shit.module.misc.AutoTool());
        this.setObj16(new shit.module.misc.BreakWarning());
        this.setObj16(new shit.module.misc.CoordsLog());
        this.setObj16(new shit.module.misc.FakeGameMode());
        this.setObj16(new shit.module.misc.FakeVanillaClient());
        this.setObj16(new shit.module.misc.LogoutLogger());
        this.setObj16(new shit.module.misc.NoSoundLag());
        this.setObj16(new shit.module.misc.SkinBlinker());
        this.setObj16(new shit.module.misc.StashLogger());
        this.setObj16(new shit.module.misc.TeleportLogger());
        this.setObj16(new shit.module.misc.UnfocusedFps());
        this.setObj16(new shit.module.player.Replenish());
        this.setObj16(new shit.module.exploit.CornerClip());
        this.setObj16(new shit.module.exploit.Disabler());
        this.setObj16(new shit.module.misc.AutoRespawn());
        this.setObj16(new shit.module.misc.AutoReconnect());
        this.setObj16(new shit.module.combat.AntiRegear());
        this.setObj16(new shit.module.combat.AutoRegear());
        this.setObj16(new shit.module.combat.AutoCrystal());
        this.setObj16(new shit.module.combat.AutoTrap());
        this.setObj16(new shit.module.exploit.MaceSpoof());
        this.setObj16(new shit.module.exploit._32kMace());
        this.setObj16(new shit.module.exploit.XCarry());
        this.setObj16(new shit.module.exploit.PingSpoof());
        this.setObj16(new shit.module.exploit.AntiHunger());
        this.setObj16(new shit.module.exploit.WallClip());
        this.setObj16(new shit.module.exploit.MountBypass());
        this.setObj16(new shit.module.player.AntiEffects());
        this.setObj16(new shit.module.player.AutoEject());
        this.setObj16(new shit.module.player.AutoEat());
        this.setObj16(new shit.module.player.Blink());
        this.setObj16(new shit.module.player.ChestStealer());
        this.setObj16(new shit.module.player.FastUse());
        this.setObj16(new shit.module.player.HandSwing());
        this.setObj16(new shit.module.player.ItemSaver());
        this.setObj16(new shit.module.player.LagNotifier());
        this.setObj16(new shit.module.player.MotionLogger());
        this.setObj16(new shit.module.player.NoPacketKick());
        this.setObj16(new shit.module.player.NoRotate());
        this.setObj16(new shit.module.player.PacketCancel());
        this.setObj16(new shit.module.player.PacketLimiter());
        this.setObj16(new shit.module.player.PacketLogger());
        this.setObj16(new shit.module.player.SwingLimiter());
        this.setObj16(new shit.module.player.ViewLock());
        this.setObj16(new shit.module.exploit.Phase());
        this.setObj16(new shit.module.misc.Tips());
        this.setObj16(new shit.module.misc.AutoLog());
        this.setObj16(new shit.module.misc.Punctuation());
        this.setObj16(new shit.module.misc.KillEffect());
        this.setObj16(new shit.module.misc.ShulkerViewer());
        this.setObj16(new shit.module.movement.FastWeb());
        this.setObj16(new shit.module.movement.VClip());
        this.setObj16(new shit.module.render.ExtraTab());
        this.setObj16(new shit.module.render.VoidESP());
        this.setObj16(new shit.module.render.NameTags());
        this.list20.sort(java.util.Comparator.comparing(m -> ((shit.module.Module) m).getText69().toLowerCase(java.util.Locale.ROOT)));
    }

    public void setObj16(Object object) {
        Module module = (Module)object;
        this.list20.add(module);
    }

    public java.util.List<shit.module.Module> getList6() {
        return this.list20;
    }

    

    public Module m979(Object object) {
        String string = (String)object;
        Iterator iterator = this.list20.iterator();
        Object var4_4 = null;
        while (iterator.hasNext()) {
            Module module = (Module)iterator.next();
            if (module.getText69().equalsIgnoreCase(string)) {
                return module;
            }
            if (null == null) continue;
        }
        return null;
    }

    public java.util.List<shit.module.Module> getByCategory(Object object) {
        shit.module.Category category = (shit.module.Category) object;
        return this.list20.stream().filter(m -> ((shit.module.Module) m).getCategory() == category)
                .map(m -> (shit.module.Module) m).toList();
    }

}

